export interface currenciesTypes {
    [key: string]: string
}

export const currencies: currenciesTypes = {
    'Afghan Afghani': "AFN",
    'Albanian Lek': "ALL",
    'Algerian Dinar': "DZD",
    'Angolan Kwanza': "AOA",
    'Argentine Peso': "ARS",
    'Armenian Dram': "AMD",
    'Aruban Florin': "AWG",
    'Australian Dollar': "AUD",
    'Azerbaijani M anat': "AZN",
    'Bahamian Dollar': "BSD",
    'Bahraini Dinar': "BHD",
    'Bajan Dollar': "BBD",
    'Bangladeshi Taka': "BDT",
    'Belarusian Ruble': "BYN",
    'Belize Dollar': "BZD",
    'Bermudan Dollar': "BMD",
    'Bhutan currency': "BTN",
    'Bolivian Boliviano': "BOB",
    'Bosnia-Herzegovina Convertible Mark': "BAM",
    'Botswanan Pula': "BWP",
    'Brazilian Real': "BRL",
    'Brunei Dollar': "BND",
    'Bulgarian Lev': "BGN",
    'Burundian Fra nc': "BIF",
    'CFP Franc': "XPF",
    'Cambodian riel': "KHR",
    'Canadian Dollar': "CAD",
    'Cape Verdean Escudo': "CVE",
    'Cayman Islands Dollar': "KYD",
    'Central African CFA Franc': "FCFA",
    'Chilean Peso': "CLP",
    'Chilean Unit of Account (UF)': "CLF",
    'Chinese Yuan (offshore)': "CNY",
    'Colombian Peso': "COP",
    'Comorian Franc': "KMF",
    'Congolese Franc': "CDF",
    'Costa Rican Colón': "CRC",
    'Croatian Kuna': "HRK",
    'Cuban Peso': "CUC",
    'Czech Koruna': "CZK",
    'Danish Krone': "DKK",
    'Djiboutian Franc': "DJF",
    'Dominican Pe so': "DOP",
    'East Caribbean Dollar': "XCD",
    'Egyptian Pound': "EGP",
    'Ethiopian Birr': "ETB",
    'Fijian Dollar': "FJD",
    'Gambian dalasi': "GMD",
    'Georgian Lari': "GEL",
    'Ghanaian Cedi': "GHS",
    'Guatemalan Quetzal': "GTQ",
    'Guinean Franc': "GNF",
    'Guyanaese Dollar': "GYD",
    'Haitian Gourde': "HTG",
    'Honduran Lempira': "HNL",
    'Hong Kong Dollar': "HKD",
    'Hungarian Forint': "HUF",
    'Icelandic Króna': "ISK",
    'Indian Rupee': "INR",
    'Indonesian Rupiah': "IDR",
    'Iranian Rial': "IRR",
    'Iraqi Dinar': "IQD",
    'Israeli New Shekel': "ILS",
    'Jamaican Dollar': "JMD",
    'Japanese Yen': "JPY",
    'Jordanian Dinar': "JOD",
    'Kazakhstani Tenge': "KZT",
    'Kenyan Shilling': "KES",
    'Kuwaiti Dinar': "KWD",
    'Kyrgystani Som': "KGS",
    'Laotian Kip': "LAK",
    'Lebanese pound': "LBP",
    'Lesotho Loti': "LSL",
    'Liberian Dollar': "LRD",
    'Libyan Dinar': "LYD",
    'Macanese Pataca': "MOP",
    'Macedonian Denar': "MKD",
    'Malagasy Ariary': "MGA",
    'Malawian Kwacha': "MWK",
    'Malaysian Ringgit': "MYR",
    'Maldivian Rufiyaa': "MVR",
    'Mauritanian Ouguiya': "MRO",
    'Mauritian Rupee': "MUR",
    'Mexican Peso': "MXN",
    'Moldovan Leu': "MDL",
    'Moroccan Dirham': "MAD",
    'Mozambican metical': "MZN",
    'Myanmar Kyat': "MMK",
    'Namibian dol lar': "NAD",
    'Nepalese Rupee': "NPR",
    'Netherlands Antillean Guilder': "ANG",
    'New Zealand Dollar': "NZD",
    'Nicaraguan Córdoba': "NIO",
    'Nigerian Naira': "NGN",
    'Norwegian Krone': "NOK",
    'Omani Rial': "OMR",
    'Pakistani Rupee': "PKR",
    'Panamanian Balboa': "PAB",
    'Papua New Guinean Kina': "PGK",
    'Paraguayan Guarani': "PYG",
    'Philippine peso': "PHP",
    'Poland Złoty': "PLN",
    'Pound sterling': "GBP",
    'Qatari Rial': "QAR",
    'Romania n Leu': "RON",
    'Russian Ruble': "RUB",
    'Rwandan franc': "RWF",
    'Salvadoran Colón': "SVC",
    'Saudi Riyal': "SAR",
    'Serbian Dinar': "RSD",
    'Seychellois Rupee': "SCR",
    'Sierra Leonean Leone': "SLL",
    'Singapore Dollar': "SGD",
    'Solomon Islands Dollar': "SBD",
    'Somali Shilling': "SOS",
    'South African Rand': "ZAR",
    'South Korean won': "KRW",
    'Sovereign Bolivar': "VES",
    'Sri Lankan Rupee': "LKR",
    'Sudanese pound': "SDG",
    'Surinamese Dollar': "SRD",
    'Swazi Lilangeni': "SZL",
    'Swedish Krona': "SEK",
    'Swiss Franc': "CHF",
    'Tajikistani Somoni': "TJS",
    'Tanzanian Shilling': "TZS",
    'Thai Baht': "THB",
    'Tongan Pa"anga': "TOP",
    'Trinidad and Tobago Dollar': "TTD",
    'Tunisian Dinar': "TND",
    'Turkish lira': "TRY",
    'Turkmenistan manat': "TMT",
    'Ugandan Shilling': "UGX",
    'Ukrainian hryvnia': "UAH",
    'United Arab Emirates Dirham': "AED",
    'United States Dollar': "USD",
    'Uruguayan Peso': "UYU",
    'Uzbekistani Som': "UZS",
    'Vietnamese dong': "VND",
    'West African CFA franc': "XOF",
    'Yemeni Rial': "YER",
    'Zambian Kwacha': "ZMW",
    'Bitcoin': "XBT",
    'Ether': "ETH",
    'Euro': "EUR",
    'Litecoin': "LTC",
    'NT$': "TWD",
    'Peruvian Sol': "PEN"
}